# NM15
INSERT INTO tournaments (id, name, language, date, deadline, fee, venue, contact, image, misc, program, details)
VALues ("nm15", "Norsk Mesterskap 2015", "no", "2015-05-17", "2015-05-16", "300 (150 for junior)", "Scandic Hotel Bergen", "endre.vestbo@gmail.com", "images/logos/nba.png", "[{\"item\": \"Bankett\", \"value\": \"Holmin spanderer!\"}]", 	"[{\"day\": \"Lørdag\", \"events\": [{\"time\": \"0800\", \"event\": \"Dørene åpner\"}, {\"time\": \"0900\", \"event\": \"Turnering starter\"}]},{\"day\": \"Søndag\", \"events\": [{\"time\": \"0800\", \"event\": \"Dørene åpner\"}, {\"time\": \"0900\", \"event\": \"Lagturnering starter\"}]}]", "[{\"title\": \"Informasjon\", \"content\": \"Lorem ipsum ...\"}, {\"title\": \"Overnatting\", \"content\": \"Lorem ipsum ...\"}]");

INSERT INTO subtournaments (tournament_id, name, type) values ("nm15", "Norsk Mesterskap", "individual");
INSERT INTO subtournaments (tournament_id, name, type) values ("nm15", "Norsk Mesterskap JR", "individual");
INSERT INTO subtournaments (tournament_id, name, type) values ("nm15", "NM Lag", "team_3");



# BO15
INSERT INTO tournaments (id, name, language, date, deadline, fee, venue, contact, image, misc, program, details)
VALues ("bo15", "Bergen Open 2015", "no", "2015-05-17", "2015-05-16", "300 (150 for junior)", "Scandic Hotel Bergen", "endre.vestbo@gmail.com", "images/logos/nba.png", "[{\"item\": \"Bankett\", \"value\": \"Holmin spanderer!\"}]", 	"[{\"day\": \"Lørdag\", \"events\": [{\"time\": \"0800\", \"event\": \"Dørene åpner\"}, {\"time\": \"0900\", \"event\": \"Turnering starter\"}]}]", "[{\"title\": \"Informasjon\", \"content\": \"Lorem ipsum ...\"}]");

INSERT INTO subtournaments (tournament_id, name, type) values ("bo15", "Bergen Open", "individual");

# TO15
INSERT INTO tournaments (id, name, language, date, deadline, fee, venue, contact, image, misc, program, details)
VALues ("to15", "Trondheim Open 2015", "no", "2015-05-17", "2015-05-16", "300 (150 for junior)", "Scandic Hotel Bergen", "endre.vestbo@gmail.com", "images/logos/nba.png", "[{\"item\": \"Bankett\", \"value\": \"Holmin spanderer!\"}]", 	"[{\"day\": \"Lørdag\", \"events\": [{\"time\": \"0800\", \"event\": \"Dørene åpner\"}, {\"time\": \"0900\", \"event\": \"Turnering starter\"}]}]", "[{\"title\": \"Informasjon\", \"content\": \"Lorem ipsum ... Endre Vestbø\"}]");

INSERT INTO subtournaments (tournament_id, name, type) values ("to15", "Bergen Open", "individual");

#nm15
INSERT INTO tournaments (id, name, language, date, deadline, fee, venue, contact, image, misc, program, details) VALUES (
	"nm15",
	"Norgesmesterskap 2015",
	"no",
	"2015-04-09",
	"2015-04-08",
	"300kr<br />For juniorar og spelarar som bur på hotellet: 200 kroner<br/>Junior-NM og U13-NM (berre fredag, gratis for dei som deltek òg i den opne klassa): 50 kroner<br />Klubb-NM (berre sundag): Gratis",
	"Scandic Ørnen",
	"Arne Johannes Holmin (patheisenberg@hotmail.com)"
	"imgs/nm.jpg",
	"[{\"item\": \"Bankett\", \"value\": \"Scandic Ørnen\"}]",
	"[{\"day\": \"Fredag\", \"events\": [{\"time\": \"15:00\", \"event\": \"Registrering og oppvarming for U13-NM\"}, {\"time\": \"16:00\", \"event\": \"U13-NM (spelare fødd 2002 eller seinare)\"}, {\"time\": \"16:00\", \"event\": \"Registrering junior-NM\"}, {\"time\": \"18:00\", \"event\": \"Junior-NM\"}, {\"time\": \"21:00\", \"event\": \"Dørene stenger\"} ]}, {\"day\": \"Lørdag\", \"events\": [{\"time\": \"08:00\", \"event\": \"Registrering og oppvarming\"}, {\"time\": \"09:00\", \"event\": \"Cup - 1., 2. og 3. runde\"}, {\"time\": \"09:30\", \"event\": \"Open klasse, grunnspel\"}, {\"time\": \"11:30\", \"event\": \"Lunsj\"}, {\"time\": \"12:30\", \"event\": \"Cup - kvartfinalar og semifinalar\"}, {\"time\": \"13:00\", \"event\": \"Open klasse, mellomspel\"}, {\"time\": \"16:00\", \"event\": \"Open klasse, sluttspel\"}, {\"time\": \"19:00\", \"event\": \"Open klasse, finale\"}, {\"time\": \"20:30\", \"event\": \"Bankett med finale i Cupen\"} ]}, {\"day\": \"Lørdag\", \"events\": [{\"time\": \"08:00\", \"event\": \"Registrering og oppvarming\"}, {\"time\": \"09:00\", \"event\": \"Klubb-NM, gruppespel\"}, {\"time\": \"11:00\", \"event\": \"Årsmøte\"}, {\"time\": \"13:00\", \"event\": \"Lunsj\"}, {\"time\": \"14:00\", \"event\": \"Klubb-NM, sluttspel\"}, {\"time\": \"16:00\", \"event\": \"Klubb-NM, finale\"}]}]",
	"[{\"title\": \"Informasjon\", \"content\": \"<p>Delta i den 22. Noregsmeisterskapen, denne gongen på det flunkande nye Scandic Ørnen midt i Bergen sentrum. Nytt av året er at heile den opne individuelle klassa vert arrangert på laurdagen, slik at Noregsmeistaren kan feirast på banketten. Juniorklassa og U13-klassa vert gjennomført på fredagen, og klubb-NM på sundagen. Cupen vert trekt tilfeldig på Debatt 20.00 si spesialsending på fredagen, og spelast laurdag, med finale på banketten. Sjå elles tidplanen for turneringsoppsettet.</p> <p>Vil nokon klara å hamla opp med den doble regjerande meisteren, veteranen Yngve Aasheim, eller vil gamlefar tangera Tore Lie si sigersrekkje frå midten av nittitalet? Kan nokon av dei nye klubbane frå Jæren og Bergen kunne hamla opp med Aasheim og resten av den regjerande doble klubb-meisteren Trondheim BHK? Kven dreg i land den tidenes fyrste U13-tittel? Kom på NM og delta i dramatikken.</p> <p>Det er premiar i A- og B-sluttspelet i den opne klassen, medaljar til topp-tre i klubb-NM, topp-tre i junior- og U13-NM, pokal til cupvinnar, pokal til vinnar av dameklassen (arrangerast berre dersom det er fire deltakarar eller fleir), og premie til beste rookie (spelarar som deltek på sitt fyrste NM).</p> <p>Årsmøtet haldast på sundagen klokken 11.00 - 12.00 midtvegs i gruppespelet i klubb-NM. Framlegg til styrekandidatar og saker sendast til patheisenberg(at)hotmail(dot)com innan fredag 10. april kl 21:00.</p> \"}, {\"title\": \"Overnatting\", \"content\": \"<p>Ting overnatting i dag for å sikra deg plass på hotellet og gode prisar på helpensjon. Helpensjonen inneheld frukost, lunsj og middag på hotellet.</p> <p>Tinging av rom gjer du ved å senda epost til meeting.ornen@scandichotels.com eller ringa +47 55 37 50 23 (Vibecke).</p> <p>Prisar på overnatting og måltid:</p> <p>Helpensjon pr pers i standard enkeltrom NOK 1 665,- per natt <br />Helpensjon pr pers i standard dobbeltrom NOK 1 180,- per natt <br />Helpensjon pr pers i standard trippelrom NOK 985,- per natt <br />Lunch for dei som ikkje bur på hotellet (per dag) NOK 295,- <br />Bankett for dei som ikke bur på hotellet NOK 445,- \"}]"
)


[{"item": "Bankett", "value": "Frøyland Klubbhus"}]

[{"day": "Fredag", "events": [{"time": "15:00", "event": "Registrering og oppvarming for U13-NM"}, {"time": "16:00", "event": "U13-NM (spelare fødd 2002 eller seinare)"}, {"time": "16:00", "event": "Registrering junior-NM"}, {"time": "18:00", "event": "Junior-NM"}, {"time": "21:00", "event": "Dørene stenger"} ]}, {"day": "Lørdag", "events": [{"time": "08:00", "event": "Registrering og oppvarming"}, {"time": "09:00", "event": "Cup - 1., 2. og 3. runde"}, {"time": "09:30", "event": "Open klasse, grunnspel"}, {"time": "11:30", "event": "Lunsj"}, {"time": "12:30", "event": "Cup - kvartfinalar og semifinalar"}, {"time": "13:00", "event": "Open klasse, mellomspel"}, {"time": "16:00", "event": "Open klasse, sluttspel"}, {"time": "19:00", "event": "Open klasse, finale"}, {"time": "20:30", "event": "Bankett med finale i Cupen"} ]}, {"day": "Lørdag", "events": [{"time": "08:00", "event": "Registrering og oppvarming"}, {"time": "09:00", "event": "Klubb-NM, gruppespel"}, {"time": "11:00", "event": "Årsmøte"}, {"time": "13:00", "event": "Lunsj"}, {"time": "14:00", "event": "Klubb-NM, sluttspel"}, {"time": "16:00", "event": "Klubb-NM, finale"}]}]

[{"title": "Informasjon", "content": "<p>Delta i den 22. Noregsmeisterskapen, denne gongen på det flunkande nye Scandic Ørnen midt i Bergen sentrum. Nytt av året er at heile den opne individuelle klassa vert arrangert på laurdagen, slik at Noregsmeistaren kan feirast på banketten. Juniorklassa og U13-klassa vert gjennomført på fredagen, og klubb-NM på sundagen. Cupen vert trekt tilfeldig på Debatt 20.00 si spesialsending på fredagen, og spelast laurdag, med finale på banketten. Sjå elles tidplanen for turneringsoppsettet.</p> <p>Vil nokon klara å hamla opp med den doble regjerande meisteren, veteranen Yngve Aasheim, eller vil gamlefar tangera Tore Lie si sigersrekkje frå midten av nittitalet? Kan nokon av dei nye klubbane frå Jæren og Bergen kunne hamla opp med Aasheim og resten av den regjerande doble klubb-meisteren Trondheim BHK? Kven dreg i land den tidenes fyrste U13-tittel? Kom på NM og delta i dramatikken.</p> <p>Det er premiar i A- og B-sluttspelet i den opne klassen, medaljar til topp-tre i klubb-NM, topp-tre i junior- og U13-NM, pokal til cupvinnar, pokal til vinnar av dameklassen (arrangerast berre dersom det er fire deltakarar eller fleir), og premie til beste rookie (spelarar som deltek på sitt fyrste NM).</p> <p>Årsmøtet haldast på sundagen klokken 11.00 - 12.00 midtvegs i gruppespelet i klubb-NM. Framlegg til styrekandidatar og saker sendast til patheisenberg(at)hotmail(dot)com innan fredag 10. april kl 21:00.</p> "}, {"title": "Overnatting", "content": "<p>Ting overnatting i dag for å sikra deg plass på hotellet og gode prisar på helpensjon. Helpensjonen inneheld frukost, lunsj og middag på hotellet.</p> <p>Tinging av rom gjer du ved å senda epost til meeting.ornen@scandichotels.com eller ringa +47 55 37 50 23 (Vibecke).</p> <p>Prisar på overnatting og måltid:</p> <p>Helpensjon pr pers i standard enkeltrom NOK 1 665,- per natt <br />Helpensjon pr pers i standard dobbeltrom NOK 1 180,- per natt <br />Helpensjon pr pers i standard trippelrom NOK 985,- per natt <br />Lunch for dei som ikkje bur på hotellet (per dag) NOK 295,- <br />Bankett for dei som ikke bur på hotellet NOK 445,- "}]

